version: "3.8"
services:
  database:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespwd
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4:6.19
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin4-data:/pgadmin4
    depends_on:
      - database
volumes:
  postgres-data:
  pgadmin4-data:
